version: '3.4'

services:
  studentrestapi:
    image: ${DOCKER_REGISTRY-}studentrestapi
    container_name: dev_netcore
    ports:
      - "5000:80"
      - "5001:443"
    build:
      context: .
      dockerfile: StudentRestAPI/Dockerfile

#  dev_postgres:
#    image: postgres:9.5
#    container_name: dev_postgres
#    restart: always
#    ports:
#      - "5555:5432"
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=students
#    volumes:
#      - dev_postgresdbdata:/var/lib/postgresql/data

#  dev_redis:
#    image: redis:latest
#    container_name: dev_redis
#    restart: always
#    ports:
#      - "6666:6379"

#volumes:
#  dev_postgresdbdata:
#    external: true
#    name: dev_postgresdbdata