version: '3.4'

services:
  #dev_netcore:
  #  image: studentrestapi:latest
  #  container_name: dev_netcore
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - ASPNETCORE_URLS=https://+:443;http://+:80
  #  ports:
  #    - "5000:80"
  #    - "5001:443"
  #  volumes:
  #    - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  #    - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  dev_postgres:
    image: postgres:9.5
    container_name: dev_postgres
    restart: always
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=students
    volumes:
      - dev_postgresdbdata:/var/lib/postgresql/data

  dev_redis:
    image: redis:latest
    container_name: dev_redis
    restart: always
    ports:
      - "6666:6379"

volumes:
  dev_postgresdbdata:
    external: true
    name: dev_postgresdbdata