version: "3"

services:
  dev_netcore:
    image: netcore:1.0
    build:
      context: .
    container_name: dev_netcore
    ports:
      - 5001:80
    links:
      - dev_redis
      - dev_postgres
    networks:
      - dev_network

  dev_postgres:
    image: postgres:9.5
    container_name: dev_postgres
    restart: always
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=students
    volumes:
      - dev_postgresdbdata:/var/lib/postgresql/data
    networks:
      - dev_network

  dev_mysql:
    image: mysql:latest
    container_name: dev_mysql
    restart: always
    ports:
      - "3333:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - dev_mysqldbdata:/var/lib/mysql

  dev_redis:
    image: redis:latest
    container_name: dev_redis
    restart: always
    ports:
      - "6666:6379"
    networks:
      - dev_network

volumes:
  dev_postgresdbdata:
    external: true
    name: dev_postgresdbdata
  dev_mysqldbdata:
    external: true
    name: dev_mysqldbdata

networks:
  dev_network:
    name: dev_network
    driver: bridge