// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudentRestAPI.Models;

namespace StudentRestAPI.Migrations
{
  [DbContext(typeof(StudentDbContext))]
  [Migration("20211118062817_InitialPostgres")]
  partial class InitialPostgres
  {
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("Relational:MaxIdentifierLength", 63)
          .HasAnnotation("ProductVersion", "5.0.8")
          .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

      modelBuilder.Entity("StudentRestAPI.Models.Student", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("integer")
                      .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

            b.Property<string>("FirstName")
                      .IsRequired()
                      .HasMaxLength(30)
                      .HasColumnType("character varying(30)");

            b.Property<decimal>("IPK")
                      .HasColumnType("numeric(4,2)");

            b.Property<string>("LastName")
                      .IsRequired()
                      .HasMaxLength(30)
                      .HasColumnType("character varying(30)");

            b.HasKey("Id");

            b.ToTable("Student");

            b.HasData(
                      new
                      {
                        Id = 1,
                        FirstName = "Zaky",
                        IPK = 3.50m,
                        LastName = "Ramadhan"
                      },
                      new
                      {
                        Id = 2,
                        FirstName = "Devina",
                        IPK = 4.00m,
                        LastName = "Ramadhani"
                      },
                      new
                      {
                        Id = 3,
                        FirstName = "Putri",
                        IPK = 3.35m,
                        LastName = "Larasati"
                      });
          });
#pragma warning restore 612, 618
    }
  }
}
